name: superres
channels:
   - pytorch
   - anaconda
   - conda-forge
   - defaults
dependencies:
   - python=3.8.8
   - torchvision==0.8.1
   - pytorch==1.8.0
   - tqdm
   - opencv
   - pip
   - pip:
      - tensorboard
      - pytorch-ssim
