name: superres
channels:
   - pytorch
   - anaconda
   - conda-forge
   - defaults
dependencies:
   - python=3.11.4
   - pytorch==2.3
   - torchvision==0.18
   - tqdm
   - opencv
   - pip
   - pip:
      - click
      - tensorboard
      - pytorch-ssim
